// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyu7wqdfpEsHxGCbZQ4xUwZw81KXzaVo',
    appId: '1:449060649620:web:dff498c1e95eb914409281',
    messagingSenderId: '449060649620',
    projectId: 'clearway-89b5d',
    authDomain: 'clearway-89b5d.firebaseapp.com',
    storageBucket: 'clearway-89b5d.firebasestorage.app',
    measurementId: 'G-EDC0Y98M7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm065afhZIJsuVI2XDxcNrFmz145GR0S4',
    appId: '1:449060649620:android:1dd94761522e7701409281',
    messagingSenderId: '449060649620',
    projectId: 'clearway-89b5d',
    storageBucket: 'clearway-89b5d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIyu7wqdfpEsHxGCbZQ4xUwZw81KXzaVo',
    appId: '1:449060649620:web:2cb49fb1564518b7409281',
    messagingSenderId: '449060649620',
    projectId: 'clearway-89b5d',
    authDomain: 'clearway-89b5d.firebaseapp.com',
    storageBucket: 'clearway-89b5d.firebasestorage.app',
    measurementId: 'G-5BED9Y196Y',
  );
}
